[2024-04-04 15:51:04,464]INFO|PNC_networking|<module>: Namespace(ae_path='saved_models/default', batch_size=4, gpu_id='0', input_size=224, joint_path='saved_models/default', log_save_path='./', mode=1, model='PNC', restart_training=False)
[2024-04-04 15:51:04,648]INFO|utils_model_pnc|asym_ae: <<<<<<<<<<<<<<<<<< RAND TAIL DROP ON >>>>>>>>>>>>>>>>>>>>>>>>
[2024-04-04 15:51:04,848]INFO|PNC_networking|<module>: <<<<<<<<<<<<<<<<<< LOAD PREVIOUS MODEL >>>>>>>>>>>>>>>>>>>>>>>>
[2024-04-04 15:51:04,848]INFO|PNC_networking|<module>:     >>> restored from saved_models/default/last_checkpoint
[2024-04-04 15:51:08,983]WARNING|functional|_conform_to_reference_input: Model was constructed with shape (None, 32, 32, 10) for input KerasTensor(type_spec=TensorSpec(shape=(None, 32, 32, 10), dtype=tf.float32, name='decoder_input'), name='decoder_input', description="created by layer 'decoder_input'"), but it was called on an input with incompatible shape (32,).
[2024-04-04 15:51:08,984]WARNING|functional|_conform_to_reference_input: Model was constructed with shape (None, 32, 32, 10) for input KerasTensor(type_spec=TensorSpec(shape=(None, 32, 32, 10), dtype=tf.float32, name='decoder_input'), name='decoder_input', description="created by layer 'decoder_input'"), but it was called on an input with incompatible shape (32,).
